version: '3.1'

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
      #- ./data:/data/db
    ports:
      - "48666:27017"


      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "48990:8081"
    depends_on:
      - mongo


  web:
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "44348:443"
        depends_on:
            - mongo
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        links:
          - mongo