version: '3.1'

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
      #- ./data:/data/db
    ports:
      - "27017:27017"
    #environment:
     #MONGO_INITDB_ROOT_USERNAME: root
     #MONGO_INITDB_ROOT_PASSWORD: pass

      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    #environment:
     #ME_CONFIG_MONGODB_ADMINUSERNAME: root
     #ME_CONFIG_MONGODB_ADMINPASSWORD: pass

  web:
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
            - "44348:443"
        depends_on:
            - mongo
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        links:
          - mongo