name: Publish Docker and DO
on: [push, workflow_dispatch]
jobs:
  build_publish_dockerhub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ypbirb/alphas_web
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: AlphaS_Web
        
  publish_DO:
    env:
      IMAGE_NAME: ypbirb/alphas_web
      COMPOSE_FOLDER: AlphaS_Web
    needs: build_publish_dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          HOST: ${{ secrets.DO_AlphaSWeb_HOST }}
          USERNAME: ${{ secrets.DO_AlphaSWeb_USERNAME }}
          PASSWORD: ${{ secrets.DO_AlphaSWeb_PASS }}
          script: |
            # Go to folder with docker-compose.yml 
            cd $(echo $COMPOSE_FOLDER)
            
            # Stop running container
            docker-compose down

            # Pull new image
            docker pull $(echo $IMAGE_NAME)
            
            # Pull full docker-compose
            docker-compose pull

            # Run a new compose container 
            docker-compose up
